spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_online?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  redis:
    host: localhost
    port: 6379
    password:
    database: 0 #操作的是0号数据库
#    jedis:
#      #Redis连接池配置
#      pool:
#        max-active: 8 #最大连接数
#        max-wait: 1ms #连接池最大阻塞等待时间
#        max-idle: 4 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false


